name: Test

on:
  workflow_call:
    inputs:
      build-matrix:
        type: string
        required: true

jobs:
  test:
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(inputs.build-matrix) }}
    uses: canonical/oci-factory/.github/workflows/Test-Rock.yaml@4b812bc455738a500c8a2deea64b1038100be997 # main
    with:
      oci-archive-name: ${{ matrix.artifact-name }}
    secrets:
      pro-artifact-passphrase: ${{ secrets[matrix.pro-artifact-passphrase] }}
